name: ğŸš€ Build and Publish Docker Images

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: ğŸ”‘ Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Backend ğŸš€
      - name: ğŸ—ï¸ Build and tag Backend Docker image
        working-directory: ./apps/api
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/firetrack-backend:nightly .
          docker tag ${{ secrets.DOCKER_USERNAME }}/firetrack-backend:nightly ${{ secrets.DOCKER_USERNAME }}/firetrack-backend:${{ github.sha }}

      - name: ğŸ“¤ Push Backend Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-backend:nightly
          docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-backend:${{ github.sha }}
    
      # Frontend ğŸ¨
      #- name: ğŸ—ï¸ Build and tag Frontend Docker image
      #  working-directory: ./apps/www
      #  run: |
      #    docker build -t ${{ secrets.DOCKER_USERNAME }}/firetrack-frontend:nightly .
      #    docker tag ${{ secrets.DOCKER_USERNAME }}/firetrack-frontend:nightly ${{ secrets.DOCKER_USERNAME }}/firetrack-frontend:${{ github.sha }}

      #- name: ğŸ“¤ Push Frontend Docker image to DockerHub
      #  run: |
      #    docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-frontend:nightly
      #    docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-frontend:${{ github.sha }}

      # Docs ğŸ“š
      - name: ğŸ—ï¸ Build and tag Docs Docker image
        working-directory: ./apps/docs
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/firetrack-docs:nightly .
          docker tag ${{ secrets.DOCKER_USERNAME }}/firetrack-docs:nightly ${{ secrets.DOCKER_USERNAME }}/firetrack-docs:${{ github.sha }}

      - name: ğŸ“¤ Push Docs Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-docs:nightly
          docker push ${{ secrets.DOCKER_USERNAME }}/firetrack-docs:${{ github.sha }}

      # Watchtower ğŸ—¼
      - name: ğŸ”„ Trigger server update
        run: |
          curl -H "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}" https://nocta-software-dsm.com/dev/ci/v1/update
